### ISSUE TITLE
statFile and loadFile with local server

### ISSUE THREAD

**Issue by Lixissimus** [LivelyKernel/lively4-core#18]
Is there a way to do a statFile and loadFile on the localhost? Right now, I am doing a `loadFile("https://lively4/templates/" + file.name)`, I don't know, what it actually does, but it grabs the files from the github API. Unfortunately, this is only allowed 60 times an hour. Is there a way do do the request on my localhost? What does the server need to implement for that? https? 
Where could I look up the service worker implementation?

**Comment by jgraichen** [comment]
Personally I develop on localhost only. It does not need HTTPS for a service worker as localhost is explicitly allowed. I'm simply serving my local `lively4-core` repository using `python -m SimpleHTTPServer 3000` and open `http://localhost:3000/draft/test.html`.

Unfortunately using `https://lively4/` as the request host the service worker will still fetch the file from GitHub but as a workaround you can use `http://localhost:3000/`. Alternatively you can change the default mounts in [`src/swx/swx.jsx#L15`](https://github.com/LivelyKernel/lively4-core/blob/gh-pages/src/swx/swx.jsx#L15) but you need to manually stop and restart the service worker. Also note that the browser will silently use the previous service worker when there is a code or runtime error in the initialization. Using `httpfs` instead of `githubfs` may work but will only support `GET` (read).

We're working on changing the mounts dynamically in your browser as well as an overlayfs and a local WebDAV filesystem.

**Comment by Lixissimus** [comment]
When changing it to `http://localhost:8002` (where my server runs, also the python SimpleHTTPServer), I get `could not stat http://localhost:8002/: Unsupported method ('OPTIONS')`.

**Comment by jgraichen** [comment]
Stat is not possible as the serve does not know what to do. This would need either a WebDAV implementation and a WebDAV file system or a client-side server implementing some swx functions.

I'll take a look at that as it may not be that hard.
