### ISSUE TITLE
Dropbox and GoogleDrive API broken

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively4-core#249]
Maybe dropbox deprecated their v1 API, maybe its a quirk of ServiceWorker in Chrome 61.

**Comment by JensLincke** [comment]
``As of today, Dropbox API v1 is deprecated. This includes both the user endpoints (a.k.a. the Core API), and the team endpoints (a.k.a. the Business API). In order to provide our developers with the most up-to-date features and support a single, consistent platform, we’ll be turning off API v1 a year from now, on 6/28/2017.`` https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by onsetsu** [comment]
Fixed Dropbox, follow up on GoogleDrive as #261
