### ISSUE TITLE
Messed up merge

### ISSUE THREAD

**Issue by adius** [LivelyKernel/lively4-core#264]
@JensLincke 

Sorry, I think i just messed up a merge: b48c51557d061d77ae062acff9b8ffe4915b5877

What exactly happened here? I just changed one file...

**Comment by adius** [comment]
I reverted it with commit bcffa5958ee0376ee7d83a57861bbf79c06ee027. Is this the correct way to fix this?

**Comment by JensLincke** [comment]
yes, I think we should be fine again. The problem was a bug in the git sync setup that let you sync while in the middle of a merge. We prevent this now. We also are aware now that it is possible to merge a branch into your own and squash it... which will lead to the problem you have observed. so only use the squash functionality in combination with sync and never with the lower level "merge" button.
