### ISSUE TITLE
How to edit the object-editor with the object-editor?

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#27]

**Comment by JensLincke** [comment]
Any ideas? @TwoLaid @espspinix

**Comment by TwoLaid** [comment]
If you have an ObjectEditor open, you can just cmd+click on it, and it will show the Halos for that ObjectEditor element. Then you can open the ObjectEditor for that ObjectEditor.

However, since the ObjectEditor hides most of its content via ShadowDOM, there isnt much to edit. So this isnt really a question of "How to edit an ObjectEditor" but rather "How to edit objects that are encapsuled in a ShadowDOM" (see #28).

One approach would be to go one level further into the ShadowDOM structure for each subsequent cmd+click, however this currently does the opposite: it selects the next parent element. So maybe alt+cmd+click could go deeper into the ShadowDOM?

**Comment by JensLincke** [comment]
CMD+SHIFT+CLICK goes currently into the deepest level and from there out...
