### ISSUE TITLE
Weird merge commit

### ISSUE THREAD

**Issue by adius** [LivelyKernel/lively4-core#276]
It made a weird merge commit again. 😓

b4ca0071e8bb5fecfcb082014798a11cf2f94011

I squashed my commits and then synced. Why didn't it work properly?

**Comment by JensLincke** [comment]
thanks for being aware, but this merge commit seems fine. This is a normal merge commit that will be automatically produced by git, because we do not do history rewriting when syncing. (but we do it when we squash). This means, that in your merge commit we see all the changes that were made since you last synced. And these were a lot, so it looks huge. But it seems ok.
