### ISSUE TITLE
binding this in "boundEval" is buggy when doing lots of parrallel evals...

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#332]
https://lively-kernel.org/lively4/lively4-jens/src/client/bound-eval.js

- example page with lots of lively-scripts that bind "this"
https://lively-kernel.org/lively4/overleaf-cop18-promises/content/implementation.md

```javascript
    // 'this' reference
    window.__global_this__ = thisReference; //  #BUG this breaks sometimes when there is a lot of async behavior... two scripts loaded in parallel ?
    ...
```
The "this" keyword is replaced in globally... here:

https://lively-kernel.org/lively4/lively4-jens/src/external/babel-plugin-doit-this-ref.js

```javascript
const GLOBAL_THIS_REPLACEMENT = '__global_this__';
//...
        path.replaceWith(t.identifier(GLOBAL_THIS_REPLACEMENT));
}
```

Idea: can we make GLOBAL_THIS_REPLACEMENT use a variable that is specific to the module / workspace / bound eval we are using?

**Comment by JensLincke** [comment]
@onsetsu  any ideas?

**Comment by onsetsu** [comment]
Hm, the original intent of bound-eval was to provide interactive code evaluation.

However, we now use bound-eval more and more in a programmatic fashion.
Even worse, as we also have more asynchronously executed code, the global *this* variable can be relevant a long time after the initial evaluation.

So, definitely a problem.

---

The same issue applies to the `targetModule` as well (https://lively-kernel.org/lively4/lively4-jens/src/client/bound-eval.js):

```JavaScript
    // binding module
    window.__topLevelVarRecorder_ModuleName__ = targetModule;
```

Here we write module-scoped variables to the wrong module instead of accessing a another this (https://lively-kernel.org/lively4/aexpr/src/external/babel-plugin-var-recorder.js):

```JavaScript
        if(DOIT_MATCHER.test(filename) && !MODULE_MATCHER.test(filename)) {
          // eval in workspace
          MODULE_NAME = window.__topLevelVarRecorder_ModuleName__;
```

---

As you suggested, to solve both issues, we would have to introduce some indirection here.
Maybe a `Map` from the uuid `path` to the respective this reference respectively module reference.
