### ISSUE TITLE
Saving and Loading duplicates

### ISSUE THREAD

**Issue by yoshikiohshima** [LivelyKernel/lively4-core#342]
When I save a world with only one workspace with 'save as', and then load it, I get three things in the loaded world. There is a thin line that is 'no id :lively-menu", and the workspace is loaded as two identical window afterwards.  In the image below, I moved one of the workspaces so their locations are different, but they perfectly overlap when the page is loaded.

<img width="775" alt="2" src="https://user-images.githubusercontent.com/197249/41879513-d81237ec-788e-11e8-87cf-5b8af0b8702c.png">

**Comment by JensLincke** [comment]
saving and loading of pages directly (e.g. booting lively  with content on a page like yoshiki3.html) as it was the practice in previous lively kernel pages is not supported, because it will conflict with loading the content saved in browser local storage (the second workspace). We always go through an emtpty start.html and load content through a lively-container..... that can be also be run in fullscreen, but gives us better control.

**Comment by JensLincke** [comment]
I disabled world saving on the body for now. What would you expect to happen after you load yoshiki.html, you edit the workspace and  reload without saving? Should content be not saved on those pages automatically? Should the new content override the old? The content in the file override the content in the local storage? By booting empty and using lively-container we have an explicit scope, without it it gets messy... any ideas?

**Comment by yoshikiohshima** [comment]
Ok, The way it works in lively4 is a bit too eager but I can live with this scheme. I'd like to create and keep different top-level worlds, though.

After updating, just reloading the page makes this duplicate and a line. So according to what you wrote, somehow I corrupted the start.html so that it is not empty anymore?  How do I verify what the start.html has?
